# Generated by Django 5.0.9 on 2024-11-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0012_alter_enrollment_course_alter_enrollment_student"),
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorfeedback",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
