# Generated by Django 5.0.9 on 2024-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_instructorfeedback_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefeedback",
            name="feedback_type",
            field=models.CharField(
                choices=[("course", "Course"), ("material", "Material")],
                default="course",
                max_length=10,
            ),
        ),
    ]
