# Generated by Django 5.0.9 on 2024-12-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_discount_course_price_and_more'),
        ('feedback', '0003_coursefeedback_helpful_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='comments',
            new_name='course_comment',
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='material_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='course.course'),
        ),
    ]
